version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
        name: Test building the docker image
        command: docker build -t ericdowell/laravel-circleci:latest .
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly-push:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
