version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
        name: Test building the docker image
        command: docker build -t ericdowell/laravel-circleci:latest .
     - run:
        name: Trigger Docker Hub Build
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            if [ -z ${DOCKER_TRIGGER_TOKEN+x} ]
            then
             echo "DOCKER_TRIGGER_TOKEN not set";
            else
             curl -X POST https://cloud.docker.com/api/build/v1/source/$DOCKER_CLOUD_SOURCE/trigger/$DOCKER_CLOUD_TRIGGER/call/
            fi
          fi
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
