version: 2
jobs:
 build:
   machine: true
   environment:
    - DOCKER_CREATE_NAME=laravel_circleci
    - DOCKER_IMG_NAME=ericdowell/laravel-circleci
   steps:
     - checkout
     - run:
        name: Test building the docker image
        command: docker build -t $DOCKER_IMG_NAME:latest .
     - run:
        name: Create Container
        command: docker create --name $DOCKER_CREATE_NAME ericdowell/laravel-circleci:latest
     - run:
        name: Start Container
        command: docker start $DOCKER_CREATE_NAME
     - run:
        name: Output Build Versions
        command: |
          echo 'supervisord:' && docker exec -ti $DOCKER_CREATE_NAME supervisord -v
          docker exec -ti $DOCKER_CREATE_NAME nginx -v
          docker exec -ti $DOCKER_CREATE_NAME php -v
          echo 'php extensions:' && docker exec -ti $DOCKER_CREATE_NAME ls /usr/local/etc/php/conf.d/
          echo 'yarn:' && docker exec -ti $DOCKER_CREATE_NAME yarn -v
          echo 'node:' && docker exec -ti $DOCKER_CREATE_NAME node -v
          echo 'npm:' && docker exec -ti $DOCKER_CREATE_NAME npm -v
     - run:
        name: Remove Container
        command: docker rm -f $DOCKER_CREATE_NAME
     - run:
        name: Push Build to Docker Hub
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            if [ -z ${DOCKER_PASS+x} ]
            then
             echo "DOCKER_PASS not set.";
            else
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push $DOCKER_IMG_NAME:latest
            fi
          else
              echo "Not the right branch to push to docker hub."
          fi
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
