version: 2
jobs:
 build:
   machine: true
   environment:
    - DOCKER_CREATE_NAME=laravel_circleci
    - DOCKER_IMG_NAME=ericdowell/laravel-circleci
   steps:
     - checkout
     - run:
        name: Test building the docker image
        command: docker build -t $DOCKER_IMG_NAME:latest .
     - run:
        name: Output Build Versions
        command: |
          docker create --name $DOCKER_CREATE_NAME ericdowell/laravel-circleci:latest
          docker start $DOCKER_CREATE_NAME
          docker exec -ti $DOCKER_CREATE_NAME nginx -v
          docker exec -ti $DOCKER_CREATE_NAME php -v
          docker rm -f $DOCKER_CREATE_NAME
     - run:
        name: Push Build to Docker Hub
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            if [ -z ${DOCKER_PASS+x} ]
            then
             echo "DOCKER_PASS not set";
            else
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push $DOCKER_IMG_NAME:latest
            fi
          fi
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
